version: '3'

services: 
    web:
        image: nginx:1.21.3
        ports:
            - "8080:80"
        volumes:
            - ./web:/var/www/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web-network
    php:
        build: ./config
        volumes:
            - ./web:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - web-network

networks:
    web-network:
        driver: bridge